"""Add role for users

Revision ID: 310f0874a155
Revises: 33988cc4fd54
Create Date: 2026-08-28 15:45:14.351970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310f0874a155'
down_revision: Union[str, Sequence[str], None] = '33988cc4fd54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('user', 'leader', 'admin', name='user_role')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', role_enum, server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('user', 'leader', 'admin', name='user_role')
    op.drop_column('users', 'role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
