"""Relationship books to users

Revision ID: 35364b298a9a
Revises: 310f0874a155
Create Date: 2026-08-29 09:09:19.449287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35364b298a9a'
down_revision: Union[str, Sequence[str], None] = '310f0874a155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
